# Site settings
title: steak.and.dune - easy dune staking
email: steakandbake@protonmail.com
baseurl: # the subpath of your site, e.g. /blog
url: steakandbake.github.io/dune # the base hostname & protocol for your site
author:
street_address: dune blockchain
city: duneville
state: web3.0
zip_code: 
country: france
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
riot_url: https://matrix.to/#/!EhZdmqoozSndhXqAGG:matrix.org?via=matrix.org
twitter_url: https://twitter.com/steakandbaker

# Build settings
markdown: kramdown
